apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "remind-ledger.fullname" . }}-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "remind-ledger.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ include "remind-ledger.fullname" . }}
  target:
    name: {{ include "remind-ledger.fullname" . }}-db
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.database.secretArn | quote }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.database.secretArn | quote }}
        property: password
