apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "remind-ledger.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "remind-ledger.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion }}
