apiVersion: v1
kind: Service
metadata:
  name: {{ include "remind-ledger.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "remind-ledger.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "remind-ledger.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
